api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Infrastructure/ApiPlatform/Mappings']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'MugApie'
    version: '0.0.1'
    show_webby: false
    exception_to_status:
        # defaults
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # custom
        App\Application\Exceptions\OrderOperationBadRequest: 400
        App\Application\Exceptions\OrderOperationFailed: 503
        App\Application\Exceptions\ProductOperationFailed: 503
        App\Application\Exceptions\UserOperationFailed: 503
