version: '3.7'

services:

  php_app:
    build:
      context: .
      target: app
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/var/www/html:delegated
      - cachevol:/var/www/html/var/cache
      - assetsvol:/var/www/html/public/bundles
    environment:
      - "DATABASE_URL=mysql://mugapie:mugapie@db:3306/mugapie?serverVersion=8.0"
      - MYSQL_HOST=db
      - MYSQL_USER=mugapie
      - MYSQL_PASSWORD=mugapie
      - MYSQL_DATABASE=mugapie
      - APP_SECRET=muggle_api_e
      - APP_ENV=dev
      - CORS_ALLOW_ORIGIN="^https?://localhost(:[0-9]+)?$$" # escape $
      - LOG_DESTINATION=php://stderr

  db:
    image: mysql:8.0
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mugapie
      - MYSQL_USER=mugapie
      - MYSQL_PASSWORD=mugapie
    volumes:
      - dbvol:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  nginx:
    image: "evild/alpine-nginx:1.11.5"
    restart: always
    links:
      - php_app
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "1080:80"

volumes:
  cachevol:
  dbvol:
  assetsvol:
