parameters:
    currency: 'USD'
    starting_balance: 10000
    shipping_costs:
        standard:
            domestic:
                mug:
                    first: 200
                    next: 100
                tshirt:
                    first: 100
                    next: 50
            international:
                mug:
                    first: 500
                    next: 250
                tshirt:
                    first: 300
                    next: 150
        express:
            domestic:
                mug:
                    first: 1000
                    next: 1000
                tshirt:
                    first: 1000
                    next: 1000

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $currency: "%currency%"
            $startingBalance: "%starting_balance%"
            $shippingCosts: "%shipping_costs%"

    App\Application\:
        resource: '../src/Application/*'

    App\Domain\:
        resource: '../src/Domain/*'

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/Infrastructure/{Doctrine/Migrations,Kernel.php}'

    App\Ui\:
        resource: '../src/Ui/*'

    App\Ui\Http\:
        resource: '../src/Ui/Http/*'
        tags: ['controller.service_arguments']

    App\Application\EventSubscriber\DomainEventCollector:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
