on:
  pull_request_target:
    branches:
      - master
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build and run Docker env
        run: docker-compose up --build -d

      - name: Run tests
        run: sleep 60 && docker-compose exec -T php_app make ci
